### ISSUE TITLE
Expected Replica states in UI

### ISSUE THREAD

**Issue by ccit-spence** [spring-cloud-samples/eureka#10]
If you have 2 Eureka instances what should the `registered-replicas`, `unavailable-replicas`, `available-replicas` show?

Currently: 
`registered-replicas` = the other server
`unavailable-replicas` = the other server
`available-replicas` = blank

Is this correct?

**Comment by andysworkshop** [comment]
This was solved for me by setting this property to true on the Eureka servers:

```
eureka:
  client:
    registerWithEureka: true
```

Since I'm using zuul as the gatekeeper I now have to forbid access to the registered eureka application so that clients don't automatically get access to eureka via service discovery.

**Comment by tietang** [comment]
eureka.client.serverUrl.defaultZone: http://192.168.1.100:8761/eureka/,http://192.168.7.101:8761/eureka/ 

change "eureka.client.serverUrl.defaultZone" true IP/hostname, don't use localhost

**Comment by aximo** [comment]
I also meet this issue
```
registered-replicas	http://127.0.0.1:8761/eureka/
unavailable-replicas	http://127.0.0.1:8761/eureka/,
available-replicas
```

I use the config like this
```
server:
  port: 8761
spring:
  application:
    name: Discovery-Server
    
eureka:
  instance:
    appname: ${spring.application.name}

  client:
    register-with-eureka: true
    service-url:
      defaultZone:  "http://127.0.0.1:8761/eureka/"
```

I use spring boot 1.3.5.RELEASE and spring-cloud-starter-eureka-server 1.1.2.RELEASE

anybody can give a help?
